import { createContext, useContext, useState, ReactNode } from "react";

export type Lang = "zh" | "en";

type Texts = Record<string, string>;

const zh: Texts = {
  // Splash
  splash_location: "XJTLU · Suzhou",
  splash_subtitle: "Your best XJTLU campus guide",
  splash_cta: "开始探索/Start Exploring →",
  splash_f1: "图片/Photos", splash_f2: "地图/Map", splash_f3: "路线/Routes", splash_f4: "集章/Stamps",
  // BottomNav
  nav_home: "主页", nav_map: "地图", nav_camera: "相机", nav_route: "路线", nav_profile: "我的",
  // HomeScreen
  home_welcome: "嗨！快来探索今天的校园吧",
  home_spots: "景点", home_routes: "路线", home_stamps: "已集章",
  home_nav: "功能导航",
  home_nav_pictures: "图片 & 地图", home_nav_route: "路线探索",
  home_nav_mystery: "盲盒路线", home_nav_custom: "自定义路线",
  home_stamp_section: "集章进度", home_stamp_label: "打卡进度",
  home_stamp_view: "查看全部集章",
  home_favs: "收藏的路线",
  home_no_favs: "还没有收藏的路线", home_no_favs_sub: "去路线页面收藏你喜欢的路线吧",
  home_explore: "去探索路线 →",
  home_about_title: "关于 XJTLU",
  home_about_text: "西交利物浦大学坐落于苏州工业园区，融汇中西方教育精华，是中英合办的国际化研究型大学。",
  home_search_title: "搜索教室", home_search_ph: "输入教室号或楼栋，如 SA101 / 科技楼",
  home_search_hint: "💡 支持搜索教室号或楼栋名称",
  home_not_found: "未找到相关教室", home_not_found_sub: "请尝试其他关键词",
  home_start_nav: "✅ 开始导航",
  home_walk: "🚶 步行路线", home_floor_nav: "🏢 楼内导航", home_arrive: "到达教室",
  home_elev: "推荐乘坐电梯", home_stairs: "推荐走楼梯", home_no_elev: "无需乘梯",
  home_floor: "{n}楼", home_stops: "站",
  home_classroom_nav: "教室导航",
  home_more_rooms: "输入关键词搜索更多教室…",
  // Map
  map_title: "图片 & 地图", map_subtitle: "校园风光与导航",
  map_photos: "校园图片", map_map: "校园地图",
  map_tab_map: "地图", map_tab_live: "实时定位", map_locating: "正在定位中…",
  map_search: "搜索教室", map_search_ph: "输入教室号或楼栋，如 SA101 / 科技楼",
  map_hint: "💡 显示常用教室 · 输入关键词精准搜索",
  map_not_found: "未找到相关教室", map_not_found_sub: "请尝试其他关键词",
  map_more: "输入关键词搜索更多教室…", map_done: "让我们出发吧！",
  map_walk: "🚶 步行路线", map_floor_nav: "🏢 楼内导航", map_arrive: "到达教室",
  map_elev: "推荐乘坐电梯", map_stairs: "推荐走楼梯", map_no_elev: "无需乘梯",
  map_floor: "{n}楼",
  // Route
  route_title: "路线探索", route_subtitle: "选择你今天的校园旅程",
  route_mystery: "盲盒路线", route_mystery_sub: "回答问题，解锁专属惊喜路线 ✨",
  route_custom: "自定义路线", route_custom_sub: "自由选择建筑，智能生成最优路径 🔧",
  route_recommended: "推荐路线",
  route_start: "开始导览", route_new: "NEW",
  route_stops: "站",
  // Mystery
  mystery_title: "盲盒路线", mystery_subtitle: "测出你今天的专属路线",
  mystery_q: "今天的你，是哪种状态？✨",
  mystery_q_sub: "选一个最接近此刻心情的选项",
  mystery_generating: "正在生成专属路线…", mystery_analyzing: "根据你的心情分析中",
  mystery_detail: "路线详情",
  mystery_start: "开始导览",
  mystery_opt_a_title: "充电模式", mystery_opt_a_desc: "安静充实，享受独处",
  mystery_opt_b_title: "漫步模式", mystery_opt_b_desc: "放慢脚步，感受自然",
  mystery_opt_c_title: "运动模式", mystery_opt_c_desc: "精力充沛，释放活力",
  mystery_opt_d_title: "探索模式", mystery_opt_d_desc: "好奇心旺盛，发现惊喜",
  mystery_res_a: "图书馆知识之旅", mystery_res_a_tag: "静下心，在知识的海洋中徜徉",
  mystery_res_b: "自然风光之旅", mystery_res_b_tag: "漫步绿意盎然，感受校园的温柔",
  mystery_res_c: "活力健身之旅", mystery_res_c_tag: "动起来！感受校园活力四射",
  mystery_res_d: "文艺创意之旅", mystery_res_d_tag: "发现校园里的艺术气息",
  mystery_back: "路线探索",
  // Custom
  custom_title: "自定义路线", custom_subtitle: "选择建筑 · 智能规划最优路径",
  custom_selected: "已选", custom_min2: "至少 2 个", custom_ready: "可生成路线",
  custom_all: "全部",
  custom_gen_ready: "生成最优路线", custom_gen_hint: "至少选择 2 个地点", custom_planning: "正在规划路线…",
  custom_my_route: "🧩 我的自定义路线",
  custom_detail: "📍 路线详情（距离优化）",
  custom_walk: "步行约 {n} 分钟",
  custom_start: "开始导览", custom_reselect: "重新选择", custom_start_pt: "起点",
  custom_n_places: "{n} 个地点",
  custom_back: "路线探索",
  // Profile
  profile_subtitle: "XJTLU · 大一新生",
  profile_stamps: "已集章", profile_photos: "已拍照", profile_favs: "收藏路线",
  profile_tab_stamps: "集章", profile_tab_favs: "收藏路线",
  profile_progress: "打卡总进度",
  profile_remaining: "还差 {n} 个完成全部旅程 🚀",
  profile_photo_hint: "每拍一张楼照片，自动解锁对应印章",
  profile_photo_hint2: "点下方「拍照」按钮打卡",
  profile_go_photo: "去拍照",
  profile_start_route: "开始新路线探索",
  profile_no_favs: "还没有收藏的路线",
  profile_no_favs_sub: "去探索并收藏你喜欢的路线吧！",
  profile_explore: "去探索路线 →", profile_more: "探索更多路线",
  profile_edit: "编辑", profile_save: "保存",
  profile_name_default: "未命名用户",
  // Stamps
  s_library: "图书馆", s_square: "广场", s_gate: "北门",
  s_gym: "体育馆", s_canteen: "食堂", s_lake: "南湖",
  s_art: "艺术楼", s_research: "科研楼", s_maker: "创客空间",
  s_history: "校史馆", s_dorm: "学生宿舍", s_admin: "行政楼",
  // Buildings (custom route)
  b_gate: "北门", b_admin: "行政楼", b_library: "图书馆", b_square: "广场",
  b_gym: "体育馆", b_canteen: "食堂", b_lake: "南湖", b_art: "艺术楼",
  b_research: "科研楼", b_dorm: "学生宿舍", b_history: "校史馆", b_maker: "创客空间",
  // Building categories
  cat_all: "全部", cat_academic: "学术", cat_sports: "运动", cat_leisure: "休闲",
  cat_dining: "餐饮", cat_arts: "文艺", cat_nature: "自然", cat_living: "生活",
  cat_culture: "文化", cat_innovation: "创新", cat_entrance: "出入口", cat_admin_type: "行政",
  // Route types
  type_recommended: "推荐", type_mystery: "盲盒", type_custom: "自定义",
  // Access types
  acc_elev: "电梯", acc_stairs: "楼梯", acc_direct: "直达",
  acc_rec_elev: "推荐乘坐电梯", acc_rec_stairs: "推荐走楼梯", acc_rec_none: "无需乘梯",
  acc_elev_tag: "🛗 电梯", acc_stairs_tag: "🪜 楼梯", acc_direct_tag: "🚶 直达",
  // Route stops
  stop_gate:"北门", stop_admin: "行政楼", stop_library: "图书馆",
  stop_square: "广场", stop_gym: "体育馆", stop_canteen: "食堂",
  stop_lake: "南湖", stop_art: "艺术楼", stop_research: "科研楼",
  stop_dorm: "学生宿舍", stop_history: "校史馆", stop_maker: "创业中心",
  stop_selfStudy: "自习室", stop_garden: "北花园", stop_path: "林荫小道",
  stop_track: "田径跑道", stop_basket: "篮球场", stop_pool: "游泳馆",
  stop_resources: "学术资源中心",
  stop_lakeside: "南湖湖畔", stop_maingate: "主校门", stop_teaching_complex: "教学楼群",
  nav_start_pt: "出发点",
  // Photo tags
  tag_square: "name1", tag_academic: "name2", tag_nature: "name3", tag_building: "name4", tag_sports: "name5",
  // Photo titles
  photo_square: "photo1", photo_library: "photo2", photo_path: "photo3",
  photo_teaching: "photo4", photo_sports: "photo5",
  // Map pins
  pin_library: "图书馆", pin_square: "广场", pin_teaching: "教学楼",
  pin_canteen: "食堂", pin_gym: "体育馆",
  // Building names (classrooms)
  cl_sa: "理科楼A (SA)", cl_sb: "理科楼B (SB)", cl_cb: "中心楼 (CB)",
  cl_ee: "电子楼 (EE)", cl_ms: "数学楼 (MA)", cl_lb: "图书馆 (LB)",
  cl_ib: "国际楼 (IR)", cl_es: "工程楼 (EB)",
  // Route names
  route_freshman: "新生入门路线", route_parent: "家长来访路线", route_deep: "深度探索路线",
  // Camera overlay
  camera_title: "📸 校园拍照",
  camera_subtitle: "拍照打卡 · 解锁集章",
  camera_count: "已拍 {n} 张",
  camera_shoot: "立即拍照",
  camera_album: "从相册选择",
  camera_hint: "每张照片解锁一枚集章印章 🎖️",
  camera_empty_title: "拍摄校园建筑照片",
  camera_empty_sub: "每拍一张楼照片，就能解锁\n一枚对应地点的集章印章",
  camera_saved: "已保存 {n} 张照片 👇",
  camera_stamp_unlocked: "🎖️ 印章解锁：{name}",
  camera_photo_alt: "打卡照片",
  // Error page
  error_unknown: "发生了未知错误",
  error_404: "找不到该页面",
  error_generic: "错误 {n}",
  error_title: "哎呀，出错了！",
  error_back_home: "返回首页",
  // Route planning (map overlay)
  nav_plan_route: "路线规划",
  nav_your_loc: "你在这里",
  nav_est_walk: "预计步行",
  nav_distance: "距离",
  nav_walking: "🚶 步行",
  nav_gps_coming: "实时 GPS 导航即将上线",
  nav_route_hint: "后续将接入真实定位与路径规划引擎",
  nav_planning: "正在规划路线…",
  nav_route_ready_btn: "路线已规划好 ✓",
};

const en: Texts = {
  splash_location: "XJTLU · Suzhou",
  splash_subtitle: "Your best XJTLU campus guide",
  splash_cta: "Start Exploring →",
  splash_f1: "Photos", splash_f2: "Map", splash_f3: "Routes", splash_f4: "Stamps",
  nav_home: "Home", nav_map: "Map", nav_camera: "Camera", nav_route: "Route", nav_profile: "Me",
  home_welcome: "Hello! Let's explore campus today",
  home_spots: "Spots", home_routes: "Routes", home_stamps: "Stamps",
  home_nav: "Navigation",
  home_nav_pictures: "Photos & Map", home_nav_route: "Route Explorer",
  home_nav_mystery: "Mystery Route", home_nav_custom: "Custom Route",
  home_stamp_section: "Stamp Progress", home_stamp_label: "Progress",
  home_stamp_view: "View All Stamps",
  home_favs: "Favorite Routes",
  home_no_favs: "No favorites yet", home_no_favs_sub: "Explore routes and save your favorites",
  home_explore: "Explore Routes →",
  home_about_title: "About XJTLU",
  home_about_text: "Xi'an Jiaotong-Liverpool University is located in Suzhou Industrial Park, blending Eastern and Western education as an international research university.",
  home_search_title: "Find Classroom", home_search_ph: "Enter room or building, e.g. SA101",
  home_search_hint: "💡 Search by room number or building name",
  home_not_found: "No rooms found", home_not_found_sub: "Try a different keyword",
  home_start_nav: "✅ Start Navigation",
  home_walk: "🚶 Walking Route", home_floor_nav: "🏢 Indoor Navigation", home_arrive: "Arrive at Room",
  home_elev: "Take Elevator", home_stairs: "Use Stairs", home_no_elev: "No Elevator Needed",
  home_floor: "F{n}", home_stops: "stops",
  home_classroom_nav: "Classroom Nav",
  home_more_rooms: "Type to search more rooms…",
  map_title: "Photos & Map", map_subtitle: "Campus views & navigation",
  map_photos: "Campus Photos", map_map: "Campus Map",
  map_tab_map: "Map", map_tab_live: "Live Location", map_locating: "Locating…",
  map_search: "Find Classroom", map_search_ph: "Enter room or building, e.g. SA101",
  map_hint: "💡 Showing common rooms · Type to search",
  map_not_found: "No rooms found", map_not_found_sub: "Try a different keyword",
  map_more: "Type to search more rooms…", map_done: "Let's go!",
  map_walk: "🚶 Walking Route", map_floor_nav: "🏢 Indoor Navigation", map_arrive: "Arrive at Room",
  map_elev: "Take Elevator", map_stairs: "Use Stairs", map_no_elev: "No Elevator Needed",
  map_floor: "F{n}",
  route_title: "Route Explorer", route_subtitle: "Choose your campus journey today",
  route_mystery: "Mystery Route", route_mystery_sub: "Answer a question, unlock your surprise route ✨",
  route_custom: "Custom Route", route_custom_sub: "Choose buildings, get the optimal path 🔧",
  route_recommended: "Recommended Routes",
  route_start: "Start Tour", route_new: "NEW",
  route_stops: "stops",
  mystery_title: "Mystery Route", mystery_subtitle: "Discover your unique route today",
  mystery_q: "How are you feeling today? ✨",
  mystery_q_sub: "Pick the option closest to your mood right now",
  mystery_generating: "Generating your route…", mystery_analyzing: "Analyzing your mood",
  mystery_detail: "Route Details",
  mystery_start: "Start Tour",
  mystery_opt_a_title: "Recharge Mode", mystery_opt_a_desc: "Quiet & fulfilling, enjoy solitude",
  mystery_opt_b_title: "Stroll Mode", mystery_opt_b_desc: "Slow down, feel the nature",
  mystery_opt_c_title: "Active Mode", mystery_opt_c_desc: "Full of energy, release vitality",
  mystery_opt_d_title: "Explorer Mode", mystery_opt_d_desc: "Curious, discover surprises",
  mystery_res_a: "Library Knowledge Journey", mystery_res_a_tag: "Calm down in a sea of knowledge",
  mystery_res_b: "Nature Scenery Journey", mystery_res_b_tag: "Stroll through campus greenery",
  mystery_res_c: "Active Fitness Journey", mystery_res_c_tag: "Feel the campus energy!",
  mystery_res_d: "Arts & Culture Journey", mystery_res_d_tag: "Discover the artistic side of campus",
  mystery_back: "Route Explorer",
  custom_title: "Custom Route", custom_subtitle: "Choose buildings · Smart route planning",
  custom_selected: "Selected", custom_min2: "at least 2", custom_ready: "Ready to generate",
  custom_all: "All",
  custom_gen_ready: "Generate Route", custom_gen_hint: "Select at least 2 places", custom_planning: "Planning route…",
  custom_my_route: "🧩 My Custom Route",
  custom_detail: "📍 Route Details (Optimized)",
  custom_walk: "~{n} min walk",
  custom_start: "Start Tour", custom_reselect: "Reselect", custom_start_pt: "Start",
  custom_n_places: "{n} place(s)",
  custom_back: "Route Explorer",
  profile_subtitle: "XJTLU · Freshman",
  profile_stamps: "Stamps", profile_photos: "Photos", profile_favs: "Favorites",
  profile_tab_stamps: "Stamps", profile_tab_favs: "Favorites",
  profile_progress: "Overall Progress",
  profile_remaining: "{n} more to complete all! 🚀",
  profile_photo_hint: "Take a photo of a building to unlock its stamp",
  profile_photo_hint2: "Tap the Camera button below",
  profile_go_photo: "Take Photo",
  profile_start_route: "Start New Route",
  profile_no_favs: "No favorites yet",
  profile_no_favs_sub: "Explore routes and save your favorites!",
  profile_explore: "Explore Routes →", profile_more: "More Routes",
  profile_edit: "Edit", profile_save: "Save",
  profile_name_default: "Unnamed User",
  s_library: "Library", s_square: "Square", s_gate: "North Gate",
  s_gym: "Gymnasium", s_canteen: "Canteen", s_lake: "South Lake",
  s_art: "Art Center", s_research: "Research Bldg", s_maker: "Makerspace",
  s_history: "History Hall", s_dorm: "Dormitory", s_admin: "Admin Bldg",
  b_gate: "North Gate", b_admin: "Admin Bldg", b_library: "Library", b_square: "Square",
  b_gym: "Gymnasium", b_canteen: "Canteen", b_lake: "South Lake", b_art: "Art Center",
  b_research: "Research Bldg", b_dorm: "Dormitory", b_history: "History Hall", b_maker: "Makerspace",
  cat_all: "All", cat_academic: "Academic", cat_sports: "Sports", cat_leisure: "Leisure",
  cat_dining: "Dining", cat_arts: "Arts", cat_nature: "Nature", cat_living: "Living",
  cat_culture: "Culture", cat_innovation: "Innovation", cat_entrance: "Entrance", cat_admin_type: "Admin",
  type_recommended: "Rec", type_mystery: "Mystery", type_custom: "Custom",
  acc_elev: "Elevator", acc_stairs: "Stairs", acc_direct: "Direct",
  acc_rec_elev: "Take Elevator", acc_rec_stairs: "Use Stairs", acc_rec_none: "No Elevator Needed",
  acc_elev_tag: "🛗 Elev.", acc_stairs_tag: "🪜 Stairs", acc_direct_tag: "🚶 Direct",
  stop_gate: "North Gate", stop_admin: "Admin Bldg", stop_library: "Library",
  stop_square: "Square", stop_gym: "Gymnasium", stop_canteen: "Canteen",
  stop_lake: "South Lake", stop_art: "Art Center", stop_research: "Research Bldg",
  stop_dorm: "Dormitory", stop_history: "History Hall", stop_maker: "Makerspace",
  stop_selfStudy: "Study Lounge", stop_garden: "Campus Garden", stop_path: "Tree-lined Path",
  stop_track: "Running Track", stop_basket: "Basketball Court", stop_pool: "Swimming Pool",
  stop_resources: "Academic Resource Ctr",
  stop_lakeside: "South Lake Waterfront", stop_maingate: "Main Gate", stop_teaching_complex: "Teaching Bldg Complex",
  nav_start_pt: "Starting point",
  tag_square: "Square", tag_academic: "Academic", tag_nature: "Nature", tag_building: "Building", tag_sports: "Sports",
  photo_square: "Square", photo_library: "Library", photo_path: "Campus Path",
  photo_teaching: "Teaching Bldg", photo_sports: "Sports Field",
  pin_library: "Library", pin_square: "Square", pin_teaching: "Teaching Bldg",
  pin_canteen: "Canteen", pin_gym: "Gymnasium",
  cl_sa: "Science Bldg A (SA)", cl_sb: "Science Bldg B (SB)", cl_cb: "Central Bldg (CB)",
  cl_ee: "Electronics Bldg (EE)", cl_ms: "Math Bldg (MS)", cl_lb: "Library (LB)",
  cl_ib: "International Bldg (IB)", cl_es: "Engineering Bldg (ES)",
  route_freshman: "Freshman Orientation", route_parent: "Parent Visit", route_deep: "Deep Exploration",
  // Camera overlay
  camera_title: "📸 Campus Photos",
  camera_subtitle: "Snap & Unlock Stamps",
  camera_count: "Photos: {n}",
  camera_shoot: "Take Photo",
  camera_album: "Choose from Album",
  camera_hint: "Each photo unlocks a stamp 🎖️",
  camera_empty_title: "Photograph Campus Buildings",
  camera_empty_sub: "Each building photo unlocks\na location stamp",
  camera_saved: "{n} photos saved 👇",
  camera_stamp_unlocked: "🎖️ Stamp Unlocked: {name}",
  camera_photo_alt: "Campus photo",
  // Error page
  error_unknown: "An unexpected error occurred",
  error_404: "Page not found",
  error_generic: "Error {n}",
  error_title: "Oops, something went wrong!",
  error_back_home: "Back to Home",
  // Route planning (map overlay)
  nav_plan_route: "Plan Route",
  nav_your_loc: "You are here",
  nav_est_walk: "Est. Walk",
  nav_distance: "Distance",
  nav_walking: "🚶 Walking",
  nav_gps_coming: "Live GPS Navigation Coming Soon",
  nav_route_hint: "Real-time location & routing will be integrated later",
  nav_planning: "Planning route…",
  nav_route_ready_btn: "Route Ready ✓",
};

interface LangContextValue {
  lang: Lang;
  toggle: () => void;
  t: (key: string, vars?: Record<string, string | number>) => string;
}

const LangContext = createContext<LangContextValue>({
  lang: "zh",
  toggle: () => {},
  t: (k) => k,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>("zh");
  const toggle = () => setLang((l) => (l === "zh" ? "en" : "zh"));
  const t = (key: string, vars?: Record<string, string | number>) => {
    const map = lang === "zh" ? zh : en;
    let str = map[key] ?? key;
    if (vars) {
      Object.entries(vars).forEach(([k, v]) => {
        str = str.replace(`{${k}}`, String(v));
      });
    }
    return str;
  };
  return <LangContext.Provider value={{ lang, toggle, t }}>{children}</LangContext.Provider>;
}

export function useLanguage() {
  return useContext(LangContext);
}