import { createContext, useContext, useState, ReactNode } from "react";

export type Lang = "zh" | "en";

type Texts = Record<string, string>;

const zh: Texts = {
  // Splash
  splash_location: "XJTLU · Suzhou",
  splash_subtitle: "Your best XJTLU campus guide",
  splash_cta: "开始探索/Start Exploring →",
  splash_f1: "图片/Photos", splash_f2: "地图/Map", splash_f3: "路线/Routes", splash_f4: "集章/Stamps",
  // BottomNav
  nav_home: "主页", nav_map: "地图", nav_camera: "相机", nav_route: "路线", nav_profile: "我的",
  // HomeScreen
  home_welcome: "嗨！快来探索今天的校园吧",
  home_spots: "景点", home_routes: "路线", home_stamps: "已集章",
  home_nav: "功能导航",
  home_nav_pictures: "图片 & 地图", home_nav_route: "路线探索",
  home_nav_mystery: "盲盒路线", home_nav_custom: "自定义路线",
  home_stamp_section: "集章进度", home_stamp_label: "打卡进度",
  home_stamp_view: "查看全部集章",
  home_favs: "收藏的路线",
  home_no_favs: "还没有收藏的路线", home_no_favs_sub: "去路线页面收藏你喜欢的路线吧",
  home_explore: "去探索路线 →",
  home_about_title: "关于 XJTLU",
  home_about_text: "西交利物浦大学坐落于苏州工业园区，融汇中西方教育精华，是中英合办的国际化研究型大学。",
  home_search_title: "搜索教室", home_search_ph: "输入教室号或楼栋，如 SA101 / 科技楼",
  home_search_hint: "💡 支持搜索教室号或楼栋名称",
  home_not_found: "未找到相关教室", home_not_found_sub: "请尝试其他关键词",
  home_start_nav: "✅ 开始导航",
  home_walk: "🚶 步行路线", home_floor_nav: "🏢 楼内导航", home_arrive: "到达教室",
  home_elev: "推荐乘坐电梯", home_stairs: "推荐走楼梯", home_no_elev: "无需乘梯",
  home_floor: "{n}楼", home_stops: "站",
  home_classroom_nav: "教室导航",
  home_more_rooms: "输入关键词搜索更多教室…",
  // Map
  map_title: "图片 & 地图", map_subtitle: "校园风光与导航",
  map_photos: "校园图片", map_map: "校园地图",
  map_tab_map: "地图", map_tab_live: "实时定位", map_locating: "正在定位中…",
  map_search: "搜索教室", map_search_ph: "输入教室号或楼栋，如 SA101 / 科技楼",
  map_hint: "💡 显示常用教室 · 输入关键词精准搜索",
  map_not_found: "未找到相关教室", map_not_found_sub: "请尝试其他关键词",
  map_more: "输入关键词搜索更多教室…", map_done: "让我们出发吧！",
  map_convenience: "校园便民",
  map_convenience_desc: "快速查看校园便民点位，方便应急使用。",
  map_convenience_sanitary: "卫生巾/湿纸巾自动售卖机",
  map_convenience_umbrella: "雨伞借用点",
  map_convenience_smoking: "吸烟区",
  map_convenience_sanitary_locs: "IRG14 / BSG43 / BSG57 / BSG26 / FBG38",
  map_convenience_umbrella_locs: "CB3 前台接待处",
  map_convenience_smoking_locs: "CB 南门口",
  map_walk: "🚶 步行路线", map_floor_nav: "🏢 楼内导航", map_arrive: "到达教室",
  map_elev: "推荐乘坐电梯", map_stairs: "推荐走楼梯", map_no_elev: "无需乘梯",
  map_floor: "{n}楼",
  // Route
  route_title: "路线探索", route_subtitle: "选择你今天的校园旅程",
  route_mystery: "盲盒路线", route_mystery_sub: "回答问题，解锁专属惊喜路线 ✨",
  route_custom: "自定义路线", route_custom_sub: "自由选择建筑，智能生成最优路径 🔧",
  route_recommended: "推荐路线",
  route_start: "开始导览", route_new: "NEW",
  route_stops: "站",
  // Mystery
  mystery_title: "盲盒路线", mystery_subtitle: "测出你今天的专属路线",
  mystery_q: "今天的你，是哪种状态？✨",
  mystery_q_sub: "选一个最接近此刻心情的选项",
  mystery_generating: "正在生成专属路线…", mystery_analyzing: "根据你的心情分析中",
  mystery_detail: "路线详情",
  mystery_start: "开始导览",
  mystery_opt_food_title: "食堂美味指引", mystery_opt_food_desc: "探寻美食，味蕾的全方位满足",
  mystery_opt_store_title: "全天候补给站", mystery_opt_store_desc: "随时随地，满足你的小需求",
  mystery_opt_shuttle_title: "校园无缝穿梭", mystery_opt_shuttle_desc: "连接南中北，三校区如一",
  mystery_opt_sakura_title: "浪漫樱花季", mystery_opt_sakura_desc: "徜徉粉色花海，邂逅春日美好",
  mystery_opt_landmark_title: "地标风景线", mystery_opt_landmark_desc: "定格经典，记录校园时光",
  mystery_opt_study_title: "专注时光机", mystery_opt_study_desc: "静心学习，知识的海洋中徜徉",
  mystery_res_food: "食堂路线", mystery_res_food_tag: "南北宏远到 FB Subway，一次吃遍热门点位",
  mystery_res_store: "便利店路线", mystery_res_store_tag: "补给不掉线，串联校园高频便利店",
  mystery_res_shuttle: "南北校区穿梭路线", mystery_res_shuttle_tag: "两条南北通道 + 大路骑行，去体育馆更省力",
  mystery_res_sakura: "樱花路线", mystery_res_sakura_tag: "从 S 楼到 MB 门口，追一场春日粉色漫游",
  mystery_res_landmark: "特色地标打卡路线", mystery_res_landmark_tag: "草坪雕像、利物浦船与中心湖，一线打卡",
  mystery_res_study: "自习路线", mystery_res_study_tag: "日常学习区 + 通宵教室全覆盖",
  mystery_back: "路线探索",
  // Custom
  custom_title: "自定义路线", custom_subtitle: "选择建筑 · 智能规划最优路径",
  custom_selected: "已选", custom_min2: "至少 2 个", custom_ready: "可生成路线",
  custom_all: "全部",
  custom_gen_ready: "生成最优路线", custom_gen_hint: "至少选择 2 个地点", custom_planning: "正在规划路线…",
  custom_my_route: "🧩 我的自定义路线",
  custom_detail: "📍 路线详情（距离优化）",
  custom_walk: "步行约 {n} 分钟",
  custom_start: "开始导览", custom_reselect: "重新选择", custom_start_pt: "起点",
  custom_n_places: "{n} 个地点",
  custom_back: "路线探索",
  // Profile
  profile_subtitle: "XJTLU · 大一新生",
  profile_stamps: "已集章", profile_photos: "已拍照", profile_favs: "收藏路线",
  profile_tab_stamps: "集章", profile_tab_favs: "收藏路线",
  profile_progress: "打卡总进度",
  profile_remaining: "还差 {n} 个完成全部旅程 🚀",
  profile_photo_hint: "每次打卡拍照会随机解锁一枚徽章",
  profile_photo_hint2: "点下方「拍照」按钮打卡",
  profile_go_photo: "去拍照",
  profile_start_route: "开始新路线探索",
  profile_no_favs: "还没有收藏的路线",
  profile_no_favs_sub: "去探索并收藏你喜欢的路线吧！",
  profile_explore: "去探索路线 →", profile_more: "探索更多路线",
  profile_edit: "编辑", profile_save: "保存",
  profile_name_default: "未命名用户",
  // Stamps
  s_library: "图书馆", s_square: "广场", s_gate: "北门",
  s_gym: "体育馆", s_canteen: "食堂", s_lake: "中心湖",
  s_art: "艺术楼", s_research: "科研楼", s_maker: "创客空间",
  s_history: "校史馆", s_dorm: "学生宿舍", s_admin: "行政楼",
  // Buildings (custom route)
  b_gate: "北门", b_admin: "行政楼", b_library: "图书馆", b_square: "广场",
  b_gym: "体育馆", b_canteen: "食堂", b_lake: "中心湖", b_art: "艺术楼",
  b_research: "科研楼", b_dorm: "学生宿舍", b_history: "校史馆", b_maker: "创客空间",
  // Building categories
  cat_all: "全部", cat_academic: "学术", cat_sports: "运动", cat_leisure: "休闲",
  cat_dining: "餐饮", cat_arts: "文艺", cat_nature: "自然", cat_living: "生活",
  cat_culture: "文化", cat_innovation: "创新", cat_entrance: "出入口", cat_admin_type: "行政",
  // Route types
  type_recommended: "推荐", type_mystery: "盲盒", type_custom: "自定义",
  // Access types
  acc_elev: "电梯", acc_stairs: "楼梯", acc_direct: "直达",
  acc_rec_elev: "推荐乘坐电梯", acc_rec_stairs: "推荐走楼梯", acc_rec_none: "无需乘梯",
  acc_elev_tag: "🛗 电梯", acc_stairs_tag: "🪜 楼梯", acc_direct_tag: "🚶 直达",
  // Route stops
  stop_gate:"北门", stop_admin: "行政楼FB", stop_library: "图书馆CB",
  stop_square: "广场", stop_gym: "体育馆", stop_canteen: "食堂",
  stop_lake: "中心湖", stop_art: "影视学院", stop_research: "工科楼",
  stop_dorm: "学生宿舍", stop_history: "校史馆", stop_maker: "西浦地下创业园",
  stop_selfStudy: "自习室", stop_garden: "AS花园", stop_path: "林荫小道",
  stop_track: "田径跑道", stop_basket: "篮球场", stop_pool: "游泳馆",
  stop_resources: "学术资源中心",
  stop_lakeside: "中心湖慧吧", stop_maingate: "主校门", stop_teaching_complex: "S教学楼群",
  // Mystery route stops (new)
  stop_food_south_north_hongyuan: "南北宏远",
  stop_food_tongfa: "同发食堂",
  stop_food_mersey_cafe: "图书馆默西咖啡",
  stop_food_west_hall: "西厅",
  stop_food_east_hall: "东厅",
  stop_food_hungry: "Hungry",
  stop_food_fb_subway: "FB Subway",
  stop_store_fb: "FB 便利店",
  stop_store_library_familymart: "图书馆全家",
  stop_store_pb: "PB 便利店",
  stop_store_ir: "IR 便利店",
  stop_store_hs: "HS 便利店",
  stop_shuttle_channel_1: "南北通道路线 1",
  stop_shuttle_channel_2: "南北通道路线 2",
  stop_shuttle_main_road_gym: "骑车走大路前往体育馆",
  stop_sakura_s_building: "S 楼",
  stop_sakura_mb_gate: "MB 门口",
  stop_sakura_es: "ES 周边（可继续拓展）",
  stop_landmark_fb_lawn_statue: "FB 门口大草坪雕像",
  stop_landmark_liverpool_ship: "利物浦船",
  stop_landmark_small_white_pavilion: "小白亭",
  stop_landmark_channel_graffiti: "南北通道社团涂鸦",
  stop_landmark_south_cat_statue: "南校区小野猫雕像",
  stop_landmark_south_lake: "南校区中心湖",
  stop_study_daily_cb: "CB（平时主要区域）",
  stop_study_daily_fb: "FB（平时主要区域）",
  stop_study_daily_bs: "BS（平时主要区域）",
  stop_study_daily_zemo: "ZEMO（平时主要区域）",
  stop_study_daily_mersey: "MERSEY（平时主要区域）",
  stop_study_small_classrooms: "各教学楼小教室",
  stop_study_lecture_halls: "Lecture 教室",
  stop_study_computer_rooms: "机房",
  stop_study_overnight_fb_cb_eb_ma_sa_bs: "通宵教室：FB / CB / EB / MA / SA / BS",
  mystery_note_stop_2: "第 2 站",
  mystery_note_stop_3: "第 3 站",
  mystery_note_stop_4: "第 4 站",
  mystery_note_stop_5: "第 5 站",
  mystery_note_stop_6: "第 6 站",
  mystery_note_stop_7: "第 7 站",
  mystery_note_stop_8: "第 8 站",
  mystery_note_cycle_recommended: "推荐骑行路段",
  mystery_note_add_more: "可按花况继续加点",
  mystery_note_overnight: "夜间学习可优先此点位",
  nav_start_pt: "出发点",
  // Photo tags
  tag_square: "广场", tag_academic: "学术", tag_nature: "自然", tag_building: "建筑", tag_sports: "体育馆",
  // Photo titles
  photo_square: "Square", photo_library: "Academic", photo_path: "Nature",
  photo_teaching: "Building", photo_sports: "Gym",
  // Map pins
  pin_library: "图书馆", pin_square: "广场", pin_teaching: "教学楼",
  pin_canteen: "食堂", pin_gym: "体育馆",
  // Building names (classrooms)
  cl_sa: "理科楼A (SA)", cl_sb: "理科楼B (SB)", cl_cb: "中心楼 (CB)",
  cl_ee: "电子楼 (EE)", cl_ms: "数学楼 (MA)", cl_lb: "图书馆 (LB)",
  cl_ib: "国际楼 (IR)", cl_es: "工程楼 (EB)",
  // Route names
  route_freshman: "新生入门路线", route_parent: "家长来访路线", route_deep: "深度探索路线",
  // Camera overlay
  camera_title: "📸 校园拍照",
  camera_subtitle: "拍照打卡 · 解锁集章",
  camera_count: "已拍 {n} 张",
  camera_shoot: "立即拍照",
  camera_album: "从相册选择",
  camera_hint: "每次拍照随机解锁一枚徽章 🎖️",
  camera_empty_title: "拍摄校园建筑照片",
  camera_empty_sub: "每拍一张楼照片，就能随机解锁\n一枚新的校园徽章",
  camera_saved: "已保存 {n} 张照片 👇",
  camera_stamp_unlocked: "🎖️ 已随机解锁新徽章",
  camera_photo_alt: "打卡照片",
  // Error page
  error_unknown: "发生了未知错误",
  error_404: "找不到该页面",
  error_generic: "错误 {n}",
  error_title: "哎呀，出错了！",
  error_back_home: "返回首页",
  // Route planning (map overlay)
  nav_plan_route: "路线规划",
  nav_your_loc: "你在这里",
  nav_est_walk: "预计步行",
  nav_distance: "距离",
  nav_walking: "🚶 步行",
  nav_gps_coming: "实时 GPS 导航即将上线",
  nav_route_hint: "后续将接入真实定位与路径规划引擎",
  nav_planning: "正在规划路线…",
  nav_route_ready_btn: "路线已规划好 ✓",
};

const en: Texts = {
  splash_location: "XJTLU · Suzhou",
  splash_subtitle: "Your best XJTLU campus guide",
  splash_cta: "Start Exploring →",
  splash_f1: "Photos", splash_f2: "Map", splash_f3: "Routes", splash_f4: "Stamps",
  nav_home: "Home", nav_map: "Map", nav_camera: "Camera", nav_route: "Route", nav_profile: "Me",
  home_welcome: "Hello! Let's explore campus today",
  home_spots: "Spots", home_routes: "Routes", home_stamps: "Stamps",
  home_nav: "Navigation",
  home_nav_pictures: "Photos & Map", home_nav_route: "Route Explorer",
  home_nav_mystery: "Mystery Route", home_nav_custom: "Custom Route",
  home_stamp_section: "Stamp Progress", home_stamp_label: "Progress",
  home_stamp_view: "View All Stamps",
  home_favs: "Favorite Routes",
  home_no_favs: "No favorites yet", home_no_favs_sub: "Explore routes and save your favorites",
  home_explore: "Explore Routes →",
  home_about_title: "About XJTLU",
  home_about_text: "Xi'an Jiaotong-Liverpool University is located in Suzhou Industrial Park, blending Eastern and Western education as an international research university.",
  home_search_title: "Find Classroom", home_search_ph: "Enter room or building, e.g. SA101",
  home_search_hint: "💡 Search by room number or building name",
  home_not_found: "No rooms found", home_not_found_sub: "Try a different keyword",
  home_start_nav: "✅ Start Navigation",
  home_walk: "🚶 Walking Route", home_floor_nav: "🏢 Indoor Navigation", home_arrive: "Arrive at Room",
  home_elev: "Take Elevator", home_stairs: "Use Stairs", home_no_elev: "No Elevator Needed",
  home_floor: "F{n}", home_stops: "stops",
  home_classroom_nav: "Classroom Nav",
  home_more_rooms: "Type to search more rooms…",
  map_title: "Photos & Map", map_subtitle: "Campus views & navigation",
  map_photos: "Campus Photos", map_map: "Campus Map",
  map_tab_map: "Map", map_tab_live: "Live Location", map_locating: "Locating…",
  map_search: "Find Classroom", map_search_ph: "Enter room or building, e.g. SA101",
  map_hint: "💡 Showing common rooms · Type to search",
  map_not_found: "No rooms found", map_not_found_sub: "Try a different keyword",
  map_more: "Type to search more rooms…", map_done: "Let's go!",
  map_convenience: "Campus Convenience",
  map_convenience_desc: "Quick access to practical campus service spots for emergencies.",
  map_convenience_sanitary: "Sanitary Napkin / (Wet) Tissue Vending Machines",
  map_convenience_umbrella: "Umbrella Service Point",
  map_convenience_smoking: "Smoking Area",
  map_convenience_sanitary_locs: "IRG14 / BSG43 / BSG57 / BSG26 / FBG38",
  map_convenience_umbrella_locs: "CB3 Reception Desk",
  map_convenience_smoking_locs: "CB South Gate",
  map_walk: "🚶 Walking Route", map_floor_nav: "🏢 Indoor Navigation", map_arrive: "Arrive at Room",
  map_elev: "Take Elevator", map_stairs: "Use Stairs", map_no_elev: "No Elevator Needed",
  map_floor: "F{n}",
  route_title: "Route Explorer", route_subtitle: "Choose your campus journey today",
  route_mystery: "Mystery Route", route_mystery_sub: "Answer a question, unlock your surprise route ✨",
  route_custom: "Custom Route", route_custom_sub: "Choose buildings, get the optimal path 🔧",
  route_recommended: "Recommended Routes",
  route_start: "Start Tour", route_new: "NEW",
  route_stops: "stops",
  mystery_title: "Mystery Route", mystery_subtitle: "Discover your unique route today",
  mystery_q: "How are you feeling today? ✨",
  mystery_q_sub: "Pick the option closest to your mood right now",
  mystery_generating: "Generating your route…", mystery_analyzing: "Analyzing your mood",
  mystery_detail: "Route Details",
  mystery_start: "Start Tour",
  mystery_opt_food_title: "Canteen Flavor Guide", mystery_opt_food_desc: "Explore flavors across campus dining spots",
  mystery_opt_store_title: "All-day Supply Stops", mystery_opt_store_desc: "Get what you need anytime, anywhere",
  mystery_opt_shuttle_title: "Seamless Campus Shuttle", mystery_opt_shuttle_desc: "Connect South-Central-North as one campus",
  mystery_opt_sakura_title: "Romantic Sakura Route", mystery_opt_sakura_desc: "Walk through pink blossoms in spring",
  mystery_opt_landmark_title: "Landmark Scenic Route", mystery_opt_landmark_desc: "Capture classic campus highlights",
  mystery_opt_study_title: "Focus Time Machine", mystery_opt_study_desc: "Study quietly in a sea of knowledge",
  mystery_res_food: "Canteen Route", mystery_res_food_tag: "From Hongyuan to FB Subway, taste all popular spots",
  mystery_res_store: "Convenience Store Route", mystery_res_store_tag: "A practical supply loop of key stores",
  mystery_res_shuttle: "South-North Shuttle Route", mystery_res_shuttle_tag: "Two channels plus main-road cycling to the gym",
  mystery_res_sakura: "Sakura Route", mystery_res_sakura_tag: "From S Building to MB Gate for spring blossom views",
  mystery_res_landmark: "Landmark Check-in Route", mystery_res_landmark_tag: "From lawn statues to the central lake",
  mystery_res_study: "Study Route", mystery_res_study_tag: "Covers both daily study zones and overnight classrooms",
  mystery_back: "Route Explorer",
  custom_title: "Custom Route", custom_subtitle: "Choose buildings · Smart route planning",
  custom_selected: "Selected", custom_min2: "at least 2", custom_ready: "Ready to generate",
  custom_all: "All",
  custom_gen_ready: "Generate Route", custom_gen_hint: "Select at least 2 places", custom_planning: "Planning route…",
  custom_my_route: "🧩 My Custom Route",
  custom_detail: "📍 Route Details (Optimized)",
  custom_walk: "~{n} min walk",
  custom_start: "Start Tour", custom_reselect: "Reselect", custom_start_pt: "Start",
  custom_n_places: "{n} place(s)",
  custom_back: "Route Explorer",
  profile_subtitle: "XJTLU · Freshman",
  profile_stamps: "Stamps", profile_photos: "Photos", profile_favs: "Favorites",
  profile_tab_stamps: "Stamps", profile_tab_favs: "Favorites",
  profile_progress: "Overall Progress",
  profile_remaining: "{n} more to complete all! 🚀",
  profile_photo_hint: "Each check-in photo randomly unlocks one badge",
  profile_photo_hint2: "Tap the Camera button below",
  profile_go_photo: "Take Photo",
  profile_start_route: "Start New Route",
  profile_no_favs: "No favorites yet",
  profile_no_favs_sub: "Explore routes and save your favorites!",
  profile_explore: "Explore Routes →", profile_more: "More Routes",
  profile_edit: "Edit", profile_save: "Save",
  profile_name_default: "Unnamed User",
  s_library: "Library", s_square: "Square", s_gate: "North Gate",
  s_gym: "Gymnasium", s_canteen: "Canteen", s_lake: "South Lake",
  s_art: "Art Center", s_research: "Research Bldg", s_maker: "Makerspace",
  s_history: "History Hall", s_dorm: "Dormitory", s_admin: "Admin Bldg",
  b_gate: "North Gate", b_admin: "Admin Bldg-FB", b_library: "Library-CB", b_square: "Square",
  b_gym: "Gymnasium", b_canteen: "Canteen", b_lake: "Central Lake", b_art: "Film and Television College",
  b_research: "Engineering Building", b_dorm: "Dormitory", b_history: "History Hall", b_maker: "Underground Entrepreneurship Park",
  cat_all: "All", cat_academic: "Academic", cat_sports: "Sports", cat_leisure: "Leisure",
  cat_dining: "Dining", cat_arts: "Arts", cat_nature: "Nature", cat_living: "Living",
  cat_culture: "Culture", cat_innovation: "Innovation", cat_entrance: "Entrance", cat_admin_type: "Admin",
  type_recommended: "Rec", type_mystery: "Mystery", type_custom: "Custom",
  acc_elev: "Elevator", acc_stairs: "Stairs", acc_direct: "Direct",
  acc_rec_elev: "Take Elevator", acc_rec_stairs: "Use Stairs", acc_rec_none: "No Elevator Needed",
  acc_elev_tag: "🛗 Elev.", acc_stairs_tag: "🪜 Stairs", acc_direct_tag: "🚶 Direct",
  stop_gate: "North Gate", stop_admin: "Admin Bldg-FB", stop_library: "Library-CB",
  stop_square: "Square", stop_gym: "Gymnasium", stop_canteen: "Canteen",
  stop_lake: "Central Lake", stop_art: "Film and Television College", stop_research: "Research Bldg",
  stop_dorm: "Dormitory", stop_history: "History Hall", stop_maker: "Underground Entrepreneurship Park",
  stop_selfStudy: "Study Lounge", stop_garden: "AS Garden", stop_path: "Tree-lined Path",
  stop_track: "Running Track", stop_basket: "Basketball Court", stop_pool: "Swimming Pool",
  stop_resources: "Academic Resource Ctr",
  stop_lakeside: "Central Lake Wisdom Bar", stop_maingate: "Main Gate", stop_teaching_complex: "S Teaching Bldg Complex",
  // Mystery route stops (new)
  stop_food_south_north_hongyuan: "South/North Hongyuan",
  stop_food_tongfa: "Tongfa Canteen",
  stop_food_mersey_cafe: "Mersey Cafe (Library)",
  stop_food_west_hall: "West Hall",
  stop_food_east_hall: "East Hall",
  stop_food_hungry: "Hungry",
  stop_food_fb_subway: "FB Subway",
  stop_store_fb: "FB Convenience Store",
  stop_store_library_familymart: "FamilyMart (Library)",
  stop_store_pb: "PB Convenience Store",
  stop_store_ir: "IR Convenience Store",
  stop_store_hs: "HS Convenience Store",
  stop_shuttle_channel_1: "South-North Channel Route 1",
  stop_shuttle_channel_2: "South-North Channel Route 2",
  stop_shuttle_main_road_gym: "Cycle via main road to gym",
  stop_sakura_s_building: "S Building",
  stop_sakura_mb_gate: "MB Gate",
  stop_sakura_es: "ES Area (extendable)",
  stop_landmark_fb_lawn_statue: "FB lawn entrance statue",
  stop_landmark_liverpool_ship: "Liverpool Ship",
  stop_landmark_small_white_pavilion: "Small White Pavilion",
  stop_landmark_channel_graffiti: "South-North channel graffiti wall",
  stop_landmark_south_cat_statue: "South Campus cat statue",
  stop_landmark_south_lake: "South Campus central lake",
  stop_study_daily_cb: "CB (daily study zone)",
  stop_study_daily_fb: "FB (daily study zone)",
  stop_study_daily_bs: "BS (daily study zone)",
  stop_study_daily_zemo: "ZEMO (daily study zone)",
  stop_study_daily_mersey: "MERSEY (daily study zone)",
  stop_study_small_classrooms: "Small classrooms in teaching buildings",
  stop_study_lecture_halls: "Lecture halls",
  stop_study_computer_rooms: "Computer rooms",
  stop_study_overnight_fb_cb_eb_ma_sa_bs: "Overnight rooms: FB / CB / EB / MA / SA / BS",
  mystery_note_stop_2: "Stop 2",
  mystery_note_stop_3: "Stop 3",
  mystery_note_stop_4: "Stop 4",
  mystery_note_stop_5: "Stop 5",
  mystery_note_stop_6: "Stop 6",
  mystery_note_stop_7: "Stop 7",
  mystery_note_stop_8: "Stop 8",
  mystery_note_cycle_recommended: "Recommended cycling section",
  mystery_note_add_more: "Add more stops by blossom condition",
  mystery_note_overnight: "Recommended for late-night study",
  nav_start_pt: "Starting point",
  tag_square: "Square", tag_academic: "Academic", tag_nature: "Nature", tag_building: "Building", tag_sports: "Gym",
  photo_square: "Square", photo_library: "Academic", photo_path: "Nature",
  photo_teaching: "Building", photo_sports: "Gym",
  pin_library: "Library", pin_square: "Square", pin_teaching: "Teaching Bldg",
  pin_canteen: "Canteen", pin_gym: "Gymnasium",
  cl_sa: "Science Bldg A (SA)", cl_sb: "Science Bldg B (SB)", cl_cb: "Central Bldg (CB)",
  cl_ee: "Electronics Bldg (EE)", cl_ms: "Math Bldg (MS)", cl_lb: "Library (LB)",
  cl_ib: "International Bldg (IB)", cl_es: "Engineering Bldg (ES)",
  route_freshman: "Freshman Orientation", route_parent: "Parent Visit", route_deep: "Deep Exploration",
  // Camera overlay
  camera_title: "📸 Campus Photos",
  camera_subtitle: "Snap & Unlock Stamps",
  camera_count: "Photos: {n}",
  camera_shoot: "Take Photo",
  camera_album: "Choose from Album",
  camera_hint: "Each photo randomly unlocks one badge 🎖️",
  camera_empty_title: "Photograph Campus Buildings",
  camera_empty_sub: "Each building photo randomly unlocks\na new campus badge",
  camera_saved: "{n} photos saved 👇",
  camera_stamp_unlocked: "🎖️ Random badge unlocked",
  camera_photo_alt: "Campus photo",
  // Error page
  error_unknown: "An unexpected error occurred",
  error_404: "Page not found",
  error_generic: "Error {n}",
  error_title: "Oops, something went wrong!",
  error_back_home: "Back to Home",
  // Route planning (map overlay)
  nav_plan_route: "Plan Route",
  nav_your_loc: "You are here",
  nav_est_walk: "Est. Walk",
  nav_distance: "Distance",
  nav_walking: "🚶 Walking",
  nav_gps_coming: "Live GPS Navigation Coming Soon",
  nav_route_hint: "Real-time location & routing will be integrated later",
  nav_planning: "Planning route…",
  nav_route_ready_btn: "Route Ready ✓",
};

interface LangContextValue {
  lang: Lang;
  toggle: () => void;
  t: (key: string, vars?: Record<string, string | number>) => string;
}

const LangContext = createContext<LangContextValue>({
  lang: "zh",
  toggle: () => {},
  t: (k) => k,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>("zh");
  const toggle = () => setLang((l) => (l === "zh" ? "en" : "zh"));
  const t = (key: string, vars?: Record<string, string | number>) => {
    const map = lang === "zh" ? zh : en;
    let str = map[key] ?? key;
    if (vars) {
      Object.entries(vars).forEach(([k, v]) => {
        str = str.replace(`{${k}}`, String(v));
      });
    }
    return str;
  };
  return <LangContext.Provider value={{ lang, toggle, t }}>{children}</LangContext.Provider>;
}

export function useLanguage() {
  return useContext(LangContext);
}
